### ISSUE TITLE
Wrong Period display on the Grid

### ISSUE THREAD

**Issue by Sergiogu2021** [ItCodeNerd/ScarletChainInfoIssues#26]
I have a black in its forth week but the grid displays 1 period when I guess it should be 4, right?

![image](https://user-images.githubusercontent.com/82935908/195884815-487e995d-d7e3-43aa-ac6a-9ed9ba203911.png)

Besides, the highlight of the current period is kind of strange, it is not displayed the same:

![image](https://user-images.githubusercontent.com/82935908/195886129-4bbd354b-a5e1-4bf4-8ed4-b466fc88c9cc.png)

I would highlight it in red for better visibility.

Thank you.

**Comment by ItCodeNerd** [comment]
Good call, I will put it on my list Thanks for the feedback   From: Sergiogu2021Sent: Friday, 14 October 2022 17:39To: ItCodeNerd/ScarletChainInfoIssuesCc: SubscribedSubject: [ItCodeNerd/ScarletChainInfoIssues] Wrong Period display on the Grid (Issue #26) I have a black in its forth week but the grid displays 1 period when I guess it should be 4, right?Besides, the highlight of the current period is kind of strange, it is not displayed the same:I would highlight it in red for better visibility.Thank you.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
